@rootURL = http://localhost:5006

GET {{rootURL}}/weatherforecast/
Accept: application/json


###
GET {{rootURL}}/api/glossary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzYwODc0Nzc3LCJleHAiOjE3NjA4NzgzNzcsImlhdCI6MTc2MDg3NDc3NywiaXNzIjoiR2xvc3NhcnlBUEkiLCJhdWQiOiJHbG9zc2FyeUFQSVVzZXJzIn0.-Ct8v2xzzYUBBB5vIhUtt7OcMerTGG8YCBU22EQgNLA
Accept: application/json

###
GET {{rootURL}}/api/glossary/2
Accept: application/json

###
POST {{rootURL}}/api/glossary
Content-Type: application/json
{
  "id":0,
  "term": "New term 1",
  "definition": "Test 1 is it added new term",
  "createdBy": "Admin", 
  "status": 0
}

###
PUT {{rootURL}}/api/glossary
Content-Type: application/json
{
  "id": 4,  
  "term": "New term UPDATED",
  "definition": "Test is it added new term",
  "createdBy": "User", 
  "status": 0
}

###
PUT {{rootURL}}/api/glossary/3
Content-Type: application/json
{  
  "Email": "ljubisa@gmail.com",
  "Username": "Ljubisa" 
}

###
DELETE {{rootURL}}/api/glossary/2
Accept: application/json